[package]
name = "decoders"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
shared = { version = "0.1.0", path = "../shared" }
anyhow = "1.0.80"

# OpenSlide
openslide-rs = "2.0.1"

[features]
default = ["openslide"]

openslide = []