[env]
PORT = "3000"

DATABASES_PATH = "/home/orca/Documents/magie/_databases/"
STORES_PATH = "/home/orca/Documents/magie/_stores/"

DEV_FRONTEND_PORT = "4000" # Used in development only to allow CORS.
