[workspace]
members = [
    "decoders",
    "encoders",
    "generators",
    "macros",
    "rendering-engine",
    "shared",
]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"
opt-level = 3     # TODO: Check speed compared to 2.

[workspace.dependencies]
anyhow = "1.0.95"
axum = { version = "0.8.1", features = ["ws", "json"] }
axum_typed_multipart = "0.15.1"
chrono = "0.4.39"
dashmap = "6.1.0"
dotenvy = "0.15.7"
futures-util = "0.3.31"
image = "0.25.5"
prettyplease = "0.2.29"
proc-macro2 = "1.0.93"
quote = "1.0.38"
rayon = "1.10.0"
rusqlite = { version = "0.32.1", features = ["bundled"] }
rusqlite_migration = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
syn = "2.0.98"
tempfile = "3.17.1"
tokio = { version = "1.43.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["cors"] }
turbojpeg = { version = "1.2.2", features = ["image"] }
zarrs = { version = "0.19.2", features = ["filesystem", "gzip"] }
