[workspace]
members = ["shared", "decoders", "generators", "rendering-engine"]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"

[workspace.dependencies]
anyhow = "1.0.86"
serde = { version = "1.0.209", features = ["derive"] }