[workspace]
members = ["shared", "decoders", "encoders", "generators", "rendering-engine"]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"
opt-level = 3 # TODO: Check speed compared to 2.

[workspace.dependencies]
anyhow = "1.0.89"
axum = { version = "0.7.5", features = ["ws", "json"] }
axum_typed_multipart = "0.12.1"
dotenvy = "0.15.7"
futures-util = "0.3.30"
image = "0.25.2"
rusqlite = { version = "0.31.0", features = ["bundled"] }
rusqlite_migration = "1.2.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.127"
syn = "2.0.77"
tempfile = "3.12.0"
tokio = { version = "1.40.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors"] }
turbojpeg = { version = "1.1.1", features = ["image"] }
zarrs = "0.16.4"

