[workspace]
members = ["shared", "decoders", "encoders", "generators", "rendering-engine"]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"
opt-level = 3 # TODO: Check speed compared to 2.

[workspace.dependencies]
anyhow = "1.0.95"
axum = { version = "0.8.1", features = ["ws", "json"] }
axum_typed_multipart = "0.15.1"
dotenvy = "0.15.7"
futures-util = "0.3.31"
image = "0.25.5"
rusqlite = { version = "0.32.1", features = ["bundled"] }
rusqlite_migration = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
syn = "2.0.96"
tempfile = "3.15.0"
tokio = { version = "1.43.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["cors"] }
turbojpeg = { version = "1.2.1", features = ["image"] }
zarrs = { version = "0.19.1", features = ["filesystem", "gzip"] }
