[package]
name = "generators"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
shared = { version = "0.1.0", path = "../shared" }
anyhow = "1.0.80"

# TIAToolbox-specific
flate2 = "1.0.28"
geo-types = "0.7.13"
rayon = "1.9.0"
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
wkb = "0.7.1"

[features]
default = ["tiatoolbox"]

tiatoolbox = []