CREATE TABLE IF NOT EXISTS images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  directory_path TEXT UNIQUE NOT NULL,
  image_name TEXT NOT NULL,
  store_name TEXT NOT NULL,
  annotations_name TEXT
);

CREATE TABLE IF NOT EXISTS metadata (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  image_id INTEGER NOT NULL,
  level INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  rows INTEGER NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  FOREIGN KEY(image_id) REFERENCES images(id) ON DELETE CASCADE,
  UNIQUE(image_id, level)
);