CREATE TABLE IF NOT EXISTS images (
  name TEXT PRIMARY KEY,
  image_path TEXT NOT NULL,
  store_path TEXT NOT NULL,
  annotations_path TEXT
);

CREATE TABLE IF NOT EXISTS metadata (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  level INTEGER UNIQUE NOT NULL,
  cols INTEGER NOT NULL,
  rows INTEGER NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  FOREIGN KEY(name) REFERENCES images(name) ON DELETE CASCADE
);