name: Docker Production Image CI

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Production Image
        run: docker build . --file Dockerfile.prod --tag my-image-name:$(date +%s)
